### ISSUE TITLE
Importteri on liian tiukka/huonosti implementoitu

### ISSUE THREAD

**Issue by l-2-j** [jarnovi/alkoselain#2]
[importer.php tiedoston](../tree/master/src/importer.php#L44) `parse_row` funktiossa arvojen validointi ja parseaaminen ei toimi kunnolla.

Jos ylempänä siinä tiedostossa poistaa tuon kommentin tuon error_log edestä niin näkee mitä kaikkea virhettä siitä tulee:
```
#0 /var/www/html/importer.php(65): Drink->validate()
#1 /var/www/html/importer.php(23): Importer->parse_row()
#2 /var/www/html/refresh.php(11): Importer->__construct()
#3 {main}PHP message: Exception: Drink size_in_milliliters is invalid in /var/www/html/model.php:49
```

Noista pitäisikin joistakin riveistä tullakin virheitä (listassa on mukana muitakin tuotteita kuin juomia), mutta tällä hetkellä koodi päästää läpi yhteensä vain 6 juomaa.

**Comment by RootkitRat** [comment]
Nyt lataa kaikki juomat.
